### PR TITLE
Creating a function to compare sequences of DNA

### PR DESCRIPTION
**Pull request by hssn-20**
The functions in this file make use of the [sourmash ](https://sourmash.readthedocs.io/en/latest/api.html) library to compare sequences of DNA. There are a few parameter choices ( i.e. number of hashes and k-mer sizes) I've made default however we can change them at a later point in the future.

### CODE REVIEW

**Comment by mateibejan1** [comment]
Can we add type hints to params and rename the similarity function to contain the type of similarity computed?

**Comment by hssn-20** [comment]
Done

**Comment by hssn-20** [comment]
I've also added a function to ingest fasta files though I'm not sure if its needed.

**Review by cameronraysmith — CHANGES_REQUESTED** [review]
Many thanks @hssn-20! 

Quick question: Could you please move https://github.com/hssn-20/DNA-Diffusion/blob/1f6cddd049bb5d455ec7b4e29ebe76f1b8f52062/dna-diffusion/metrics/k_mer_based_metric.py into the `dnadiffusion/metrics` (sans "-") folder and remove the `dna-diffusion` folder?

**Comment by cameronraysmith** [comment]
Please rebase after #99 or later and resubmit so that we can see only the intended changes. 
Apologies for the inconvenience and thank you!

**Pull request closed without merging**
