### PR TITLE
add initial misc util functions, count, kl_div

### PR DESCRIPTION
**Pull request by cmvcordova**

### CODE REVIEW

**Comment by noahweber1** [comment]
Hi @cmvcordova thank you for the PR.

Can you please:

1. Link the PR to a particular ticket with explanations?
2. How is this different then KL and other metrics introduced in this notebook? Wouldnt it be better to reconcile it there since this is the starting point? https://github.com/pinellolab/DNA-Diffusion/blob/dna-diffusion/notebooks/experiments/conditional_diffusion/easy_training_Conditional_Code_to_refactor_UNET_ANNOTATED_v4%20(2).ipynb

**Comment by cmvcordova** [comment]
Hey man, sure thing

1. https://github.com/pinellolab/DNA-Diffusion/issues/14
2. These are based on the notebook indeed, however, they are being rewritten to form part of the codebase, in a comprehensive, internally consistent framework that we'll then be running experiments in.


Hope this clears it up for you. In case you have more questions I'm happy to answer them.

**Comment by noahweber1** [comment]
It sure does and yes you did write it very thoroughly.

But then if this is suppose to be part of the codebase, why not commit it directly there (meaning not as part of the nb?)

**Comment by cmvcordova** [comment]
Thanks!

Initially, for exposure, review and making sure the functions are in agreement with what the codebase team expects. Additionally, figuring out the "hows/wheres" in the codebase, before committing a final version. Ideally, the codebase should only have working and reviewed components. Showing the code as a notebook beforehand makes this transition smoother. This is only my opinion, however and am open to further suggestions regarding the pull request pipeline.

**Comment by noahweber1** [comment]
No, it makes sense what you said.

However we if we continue with this approach we run the risk that people are writing notebooks. Issuing PRs then leaving and this code never lands on the "codebase" or the main "dna-diffusion" branch.

Again this is a collective decision we make and I am fine with everything. We can gladly discuss this on saturday.

My suggestion however, since I dont see any big negatives. Is to try to marry this directly into the "codebase" branch or wait until this gets into develop.

If we go with this approach in the future, and when we have a lot of e2e running, then it will never happen that a nb implementation is good but not passing some tests.

**Comment by cmvcordova** [comment]
Great points. Let's bring them up on the Saturday meeting!

**Comment by mateibejan1** [comment]
Closed as solved in another PR.

**Pull request closed without merging**
