### PR TITLE
Chromatin accessibility data preprocessing

### PR DESCRIPTION
**Pull request by aaronwtr**
Cloned Enformer code and Deopen code into the metrics folder. Also built data conversion pipeline to transform the meuleman data from .csv to .bed, satisfying Deopen's requirements. Next step is to start training the Deopen model.

### CODE REVIEW

**Comment by noahweber1** [comment]
Hi @aaronwtr just a quick question. Why into the metrics folder?

"metrics: contains the internal metrics used to evaluate the quality of the generated sequences after training"

Would it not be better to have it under model/enformer/evaluation.py and model/deopen/evaluation.py

And in the evaluation.py files there should be clear evaluation of the two afromentioned approaches on our main dataset? https://www.meuleman.org/research/synthseqs/

Furthermore why are you merging in "dna-diffusion" when almost all changes are in "codebase". (I am with you tough, it states this is default).

Finally I see from commits that you essentially made the data in the correct format, however would it not be better to test the performance directly. Because we might be merging code and introducing complexity without even knowing wether this code performs well or interesting enough in our data.

**Comment by lucapinello** [comment]
@noahweber1 

"Would it not be better to have it under model/enformer/evaluation.py and model/deopen/evaluation.py"

No the idea is to have in model only dna-diffusion models. Here we are using enformer and deopen as external oracles to evaluate the quality of the sequences we generate.

Also the "main" branch for this project is called dna-diffusion 

Regarding performance, this is not a concern for now given the very modest size of the datasets we are going to analyze (the human genome is only 3Billion bases)

@aaronwtr  great job!

**Comment by noahweber1** [comment]
> 
Thanks for the answer. So if I am extrapolating this correctly, once we have the baseline for the diffusion based models these two (other types of models) we will be comparing them against correct?

**Comment by aaronwtr** [comment]
Hi @noahweber1, 

Thanks @lucapinello for answering! I agree with everything Luca said but just to be sure, let me try to clarify what we are trying to do here a bit further for you. 

The models here will not be used to evaluate the performance of the novel sequence generation. Rather, these models will serve as "biological oracles" to help us to assess the biological relevance and quality of the generated sequences. Simply put, we are asking the question: do our novel sequences make biological sense? If I can give an NLP analogy: we are trying to assess when we train on the Oxford English Dictionary whether our model produces nice English sentences or whether it outputs illegible text. In the NLP context, this is straightforward to see directly from the output. In the case of the DNA sequences, this is not so straightforward for us to see and hence we resort to external validation models to assess regulatory sequence quality for us. For example with Deopen, we can assess whether the generated sequences correspond to accessible or inaccessible regions of the chromatin. Similarly, Enformer could be used to evaluate gene expression-related outcomes, i.e. does this novel sequence affect some downstream gene? Would this sequence have the desired downstream effect in some given genomic context? 

Hope this helps and let me know if there is still anything unclear!

**Comment by jamesthesnake** [comment]
+1^

**Comment by noahweber1** [comment]
Hi @aaronwtr thanks for the clarification. 

You say "The models here will not be used to evaluate the performance of the novel sequence generation. Rather, these models will serve as "biological oracles" to help us to assess the biological relevance and quality of the generated sequences."

So how is evaluating the performence of the novel sequence generation different from assessing the biological relevance and quality of the generating sequence.

Isnt this the same?

In any case it definately makes sense what you said. Thanks.

**Comment by noahweber1** [comment]
Also, did you evaluate this implementation https://github.com/lucidrains/enformer-pytorch

They way I see it this would eliviate the need to copy all of the code from enformer to use and deal with this complexity? @aaronwtr

**Comment by aaronwtr** [comment]
@noahweber1 yeah it's a bit of semantics really but when you say "measuring performance" in the context of DNA diffusion, I am thinking of the optimization function we are optimizing by which we measure how well our model performs on our train and test data. I believe this currently is the KL divergence. So to avoid confusion I'd rather refer to these models as something along the lines of oracles or external validation models. Again, bit of a semantical discussion and saying that these external validation models validate the biological performance of the DNA diffusion isn't necessarily wrong, it gets really confusing when you have a lot of these metrics. 

Thanks for sharing that PyTorch implementation! DeepMind themselves released the pretrained Enformer models in tensforflow framework but since most of this project is developed in pytorch it'll be nice to have the Enformer implementation in pytorch as well. I am currently not yet working on implementing Enformer, just cloned the DeepMind Enformer codebase into here as a starting point. Reverting this and using the lucidrains implementation as the starting point would not be a problem.

**Comment by noahweber1** [comment]
Thanks for the clarification and great job.

The way I see this very important evaluation codes is that it should be abstracted away as much as possible.

Lets say you are a new contributer and you want to just quickly evaluate. In a black-box fashion it should be:

./enformer.py --i predicted_sequence

Are we agreeing on this?

Do you think we should aim in this PR to abstract it away till this point.

And in subsequent PR and work to train the models and improve them?

**Comment by aaronwtr** [comment]
Closing this pull request because: 
- Changing Deopen architecture to work in DNA diffusion context is cumbersome in Lasagne framework
- Since we have access to ChromBPNet, spending time in porting to PyTorch without guaranteeing it will work there is not the best use of our time

Future focus for the external validation metrics: 
- Implementing pretrained version of ChromBPNet 
- Experiment with using Enformer to assess regulatory sequence validity in terms of chromatin accessibility and gene expression
- Porting Deopen to PyTorch is still an option if need be. We can keep this in the back of our minds.

**Pull request closed without merging**
